#!/bin/bash

sudo chmod +x pomo
# make it as a command
sudo cp pomo /usr/bin/pomo

sudo mkdir /usr/bin/pomoimages
sudo cp pomoimages/start.jpg /usr/bin/pomoimages/start.jpg
sudo cp pomoimages/break.jpg /usr/bin/pomoimages/break.jpg
exit
